'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { db } from '@/lib/mvp/db'
import { requireAdmin,hashPassword,verifyPassword,startSession } from '@/lib/mvp/auth'
const tables={place:'vg_places',article:'vg_articles',event:'vg_events'} as const
function text(f:FormData,key:string,max=20000){return String(f.get(key)||'').trim().slice(0,max)}
function url(f:FormData,key:string){const value=text(f,key,2000);if(!value)return '';if(key==='image_url'&&/^\/[a-z0-9-]+\.(jpg|jpeg|png|webp)$/i.test(value))return value;try{const parsed=new URL(value);if(parsed.protocol!=='https:'&&parsed.protocol!=='http:')throw new Error();return parsed.href}catch{throw new Error('Alamat URL harus diawali https:// atau http://')}}
function slug(f:FormData){const value=text(f,'slug',160);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value))throw new Error('Slug hanya memakai huruf kecil, angka, dan tanda hubung.');return value}
export async function saveContent(f:FormData){await requireAdmin();const kind=text(f,'kind') as keyof typeof tables;const table=tables[kind];if(!table)throw new Error('Jenis konten tidak valid');const id=Number(f.get('id'))||null;const status=text(f,'status')==='published'?'published':'draft';const name=text(f,kind==='place'?'name':'title',200);const client=await db().connect();try{await client.query('BEGIN');if(!name)throw new Error('Judul/nama wajib diisi');const common={slug:slug(f),excerpt:text(f,'excerpt',500),content:text(f,'content'),status};let rowId=id;
 if(kind==='place'){const cat=text(f,'category');if(!['wisata','hotel','kuliner','cafe','transportasi','paket-wisata'].includes(cat))throw new Error('Kategori tidak valid');const latText=text(f,'latitude');const lonText=text(f,'longitude');const lat=latText?Number(latText):null;const lon=lonText?Number(lonText):null;if((lat!==null&&(!Number.isFinite(lat)||Math.abs(lat)>90))||(lon!==null&&(!Number.isFinite(lon)||Math.abs(lon)>180))||((lat===null)!==(lon===null)))throw new Error('Koordinat tidak valid');const values=[common.slug,name,cat,text(f,'district',120),text(f,'address',1000),common.excerpt,common.content,url(f,'image_url'),text(f,'image_credit',500),lat,lon,url(f,'website'),text(f,'whatsapp',24).replace(/\D/g,''),url(f,'source_url'),status];if(id)await client.query(`UPDATE vg_places SET slug=$1,name=$2,category=$3,district=$4,address=$5,excerpt=$6,content=$7,image_url=$8,image_credit=$9,latitude=$10,longitude=$11,website=$12,whatsapp=$13,source_url=$14,status=$15,updated_at=now() WHERE id=$16`,[...values,id]);else rowId=(await client.query(`INSERT INTO vg_places(slug,name,category,district,address,excerpt,content,image_url,image_credit,latitude,longitude,website,whatsapp,source_url,status) VALUES(${values.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING id`,values)).rows[0].id;
 }else if(kind==='article'){const values=[common.slug,name,common.excerpt,common.content,text(f,'author',120)||'Tim VisitGarut',status];if(id)await client.query(`UPDATE vg_articles SET slug=$1,title=$2,excerpt=$3,content=$4,author=$5,status=$6,published_at=CASE WHEN $6::varchar='published' THEN COALESCE(published_at,now()) ELSE published_at END,updated_at=now() WHERE id=$7`,[...values,id]);else rowId=(await client.query(`INSERT INTO vg_articles(slug,title,excerpt,content,author,status,published_at) VALUES($1,$2,$3,$4,$5,$6,CASE WHEN $6::varchar='published' THEN now() ELSE NULL END) RETURNING id`,values)).rows[0].id;await client.query('DELETE FROM vg_article_places WHERE article_id=$1',[rowId]);for(const placeId of [...new Set(f.getAll('place_ids').map(Number).filter(n=>Number.isInteger(n)&&n>0))])await client.query('INSERT INTO vg_article_places(article_id,place_id) VALUES($1,$2)',[rowId,placeId]);
 }else{const start=text(f,'starts_at',100);const end=text(f,'ends_at',100);const starts=new Date(start);const ends=end?new Date(end):null;if(Number.isNaN(starts.getTime())||(ends&&(Number.isNaN(ends.getTime())||ends<starts)))throw new Error('Tanggal event tidak valid');const values=[common.slug,name,common.excerpt,common.content,text(f,'address',1000),starts,ends,url(f,'source_url'),status];if(id)await client.query(`UPDATE vg_events SET slug=$1,title=$2,excerpt=$3,content=$4,address=$5,starts_at=$6,ends_at=$7,source_url=$8,status=$9,updated_at=now() WHERE id=$10`,[...values,id]);else rowId=(await client.query(`INSERT INTO vg_events(slug,title,excerpt,content,address,starts_at,ends_at,source_url,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,values)).rows[0].id}
 await client.query('COMMIT');revalidatePath('/','layout')
 }catch(e){await client.query('ROLLBACK');console.error('Content save failed',e instanceof Error?e.message:'unknown');redirect('/admin?error=save')}finally{client.release()}redirect('/admin?saved=1')}
export async function changePassword(f:FormData){await requireAdmin();const current=text(f,'current',200);const password=text(f,'password',200);const row=(await db().query('SELECT password_hash FROM vg_admin WHERE id=1')).rows[0];if(!verifyPassword(current,row.password_hash)||password.length<12)redirect('/admin?error=password');const hash=hashPassword(password);await db().query('UPDATE vg_admin SET password_hash=$1,updated_at=now() WHERE id=1',[hash]);await startSession(hash);redirect('/admin?saved=1')}
