'use client'
import { useEffect,useRef,useState } from 'react'
import Link from 'next/link'
import type { Map as LeafletMap } from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { categories } from '@/lib/mvp/categories'
type Pin={id:number;name:string;category:string;slug:string;district:string;latitude:number|null;longitude:number|null}
export default function MapClient({items}:{items:Pin[]}){const ref=useRef<HTMLDivElement>(null);const map=useRef<LeafletMap|null>(null);const [category,setCategory]=useState('');const [query,setQuery]=useState('');const [error,setError]=useState('');const [selected,setSelected]=useState<number|null>(null);const shown=items.filter(p=>!category||p.category===category);const listed=shown.filter(p=>(p.name+' '+p.district).toLocaleLowerCase('id-ID').includes(query.trim().toLocaleLowerCase('id-ID')));const pinned=shown.filter(p=>p.latitude!==null&&p.longitude!==null).length
 useEffect(()=>{let disposed=false;import('leaflet').then(L=>{if(disposed||!ref.current)return;const m=L.map(ref.current).setView([-7.23,107.90],10);map.current=m;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:19}).on('tileerror',()=>setError('Sebagian peta tidak dapat dimuat. Daftar tempat tetap tersedia.')).addTo(m);const points: [number,number][]=[];shown.forEach(p=>{if(p.latitude===null||p.longitude===null)return;points.push([p.latitude,p.longitude]);const link=document.createElement('a');link.href=`/${p.category}/${p.slug}`;link.textContent=p.name;L.circleMarker([p.latitude,p.longitude],{radius:9,color:'#fff',weight:3,fillColor:'#0c8a80',fillOpacity:1}).bindPopup(link).on('click',()=>setSelected(p.id)).addTo(m)});if(points.length)m.fitBounds(points,{padding:[40,40],maxZoom:12});m.invalidateSize()}).catch(()=>setError('Peta tidak dapat dimuat. Pilih tempat melalui daftar di bawah.'));return()=>{disposed=true;map.current?.remove();map.current=null}},[items,category])
 function locate(){if(!navigator.geolocation){setError('Browser ini tidak mendukung lokasi.');return}navigator.geolocation.getCurrentPosition(async pos=>{const L=await import('leaflet');if(!map.current)return;L.circleMarker([pos.coords.latitude,pos.coords.longitude],{radius:8,color:'#1263c7',fillOpacity:1}).bindPopup('Lokasimu').addTo(map.current);map.current.setView([pos.coords.latitude,pos.coords.longitude],12)},()=>setError('Lokasi tidak tersedia. Izinkan akses lokasi atau pilih tempat dari daftar.'),{timeout:10000})}
 return <><div className="vg-map-controls"><label>Kategori<select value={category} onChange={e=>{setCategory(e.target.value);setSelected(null)}}><option value="">Semua tempat</option>{[...new Set(items.map(p=>p.category))].map(c=><option value={c} key={c}>{categories.find(item=>item.slug===c)?.name||c}</option>)}</select></label><button className="vg-button" onClick={locate}>Lokasiku</button></div>{error&&<p role="status" className="vg-alert">{error}</p>}<p className="vg-count" role="status">{pinned} tempat memiliki titik peta · {shown.length-pinned} tempat tersedia melalui daftar.</p><div className="vg-map-layout"><div className="vg-map-canvas" ref={ref} aria-label="Peta interaktif Garut"/><div><label className="vg-map-search">Cari di daftar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nama tempat atau wilayah…" maxLength={120}/></label><div className="vg-map-list">{listed.map(p=><div className={selected===p.id?'selected':''} key={p.id}><button onClick={()=>{setSelected(p.id);if(p.latitude!==null&&p.longitude!==null)map.current?.setView([p.latitude,p.longitude],14)}} disabled={p.latitude===null||p.longitude===null}>{p.name}</button>{(p.latitude===null||p.longitude===null)&&<small>Titik peta belum tersedia</small>}<small>{p.district}</small><Link href={`/${p.category}/${p.slug}`}>Lihat detail</Link></div>)}{!listed.length&&<p>Tidak ada tempat yang sesuai. Coba nama atau wilayah lain.</p>}</div></div></div></>}
