import Link from 'next/link'
import { Mountain,MapPin,Search,ArrowUpRight,BedDouble,Utensils,Coffee,Car,Compass } from 'lucide-react'
import { categories,type Place,type Article } from '@/lib/mvp/data'
import { categoryHref, type DirectoryFilters } from '@/lib/mvp/categories'
import { absoluteUrl } from '@/lib/site'
export function Header(){return <header className="vg-header"><div className="vg-wrap vg-nav"><Link className="vg-brand" href="/" aria-label="VisitGarut beranda"><Mountain size={27}/><span>visit<span>garut</span><i>.</i></span></Link><nav aria-label="Navigasi utama"><Link href="/search">Jelajahi</Link><Link href="/transportasi">Rental</Link><Link href="/artikel">Panduan</Link><Link href="/community-pulse">Community Pulse</Link></nav><Link className="vg-map-button" href="/map"><MapPin size={17}/><span>Buka peta</span></Link></div></header>}
export function Footer(){return <footer className="vg-footer"><div className="vg-wrap"><strong>visitgarut.</strong><p>Panduan lokal untuk perjalananmu di Garut.</p><nav className="vg-footer-links" aria-label="Kategori direktori">{categories.map(c=><Link key={c.slug} href={`/${c.slug}`}>{c.name}</Link>)}</nav><div className="vg-footer-links"><Link href="/artikel">Artikel & panduan</Link><Link href="/event">Event & kegiatan</Link><Link href="/map">Peta Garut</Link><Link href="/community-pulse">Community Pulse</Link><Link href="/privasi">Privasi</Link><Link href="/ketentuan">Ketentuan</Link><Link href="/kredit-foto">Kredit foto</Link><Link href="/admin">Kelola konten</Link></div><small>Foto Papandayan: <a href="https://commons.wikimedia.org/wiki/File:Keindahan_alam_papandayan.jpg" target="_blank" rel="noopener noreferrer">Tantan Nurdiansyah</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>, ukuran diperkecil dan tampilan dipotong.<br/>VisitGarut adalah direktori independen. Informasi operasional dapat berubah; konfirmasi kepada pengelola sebelum berkunjung.</small></div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <><a className="vg-skip" href="#konten-utama">Lewati ke konten</a><Header/><main id="konten-utama">{children}</main><Footer/></>}
export function CategoryNav({active='',...filters}:{active?:string}&DirectoryFilters){return <nav className="vg-categories" aria-label="Kategori tempat"><Link className={!active?'active':''} aria-current={!active?'page':undefined} href={categoryHref('',filters)}>Semua tempat</Link>{categories.map(c=><Link className={active===c.slug?'active':''} aria-current={active===c.slug?'page':undefined} key={c.slug} href={categoryHref(c.slug,filters)}>{c.name}</Link>)}</nav>}
export function SearchForm({query='',category='',district=''}:{query?:string;category?:string;district?:string}){return <form className="vg-search" action="/search"><Search size={22}/><label className="sr-only" htmlFor="search-query">Cari nama tempat, layanan, atau daerah</label><input id="search-query" name="q" defaultValue={query} placeholder={category==='transportasi'?'Cari rental mobil, motor, atau penyedia…':'Cari tempat, rental, atau daerah…'} maxLength={120}/>{category&&<input type="hidden" name="category" value={category}/>}{district&&<input type="hidden" name="district" value={district}/>}<button type="submit">Cari</button></form>}
export function PlaceCard({place}:{place:Place}) {
  const cat=categories.find(c=>c.slug===place.category)
  const Icon=({wisata:Mountain,hotel:BedDouble,kuliner:Utensils,cafe:Coffee,transportasi:Car,'paket-wisata':Compass})[place.category]||MapPin
  const rental=place.category==='transportasi'
  return <Link className={`vg-card${rental&&!place.image_url?' vg-card-service':''}`} href={`/${place.category}/${place.slug}`}>
    <div className={`vg-card-image cat-${place.category}`}>
      {place.image_url?<img src={place.image_url} alt={place.name} loading="lazy" width={600} height={400}/>:<div className="vg-image-empty"><Icon size={rental?36:44} strokeWidth={1.4}/>{!rental&&<><span>{place.district || 'Garut'}</span><small>Foto belum tersedia</small></>}</div>}
      <span className="vg-tag">{cat?.name}</span>
    </div>
    <div className="vg-card-body"><p className="vg-location"><MapPin size={14}/>{place.district || 'Melayani Garut'}</p><h3>{place.name}</h3><p>{place.excerpt}</p><span className="vg-card-cta">{rental?'Info layanan & kontak':'Kenali tempat'} <ArrowUpRight size={16}/></span></div>
  </Link>
}
export function PlaceGrid({items}:{items:Place[]}){return items.length?<div className="vg-grid">{items.map(p=><PlaceCard key={p.id} place={p}/>)}</div>:<div className="vg-empty"><MapPin size={30}/><h2>Belum ada tempat yang ditampilkan</h2><p>Coba kategori atau kata pencarian lain. Direktori kami sedang bertambah.</p><Link className="vg-button" href="/search">Lihat semua tempat</Link></div>}
export function ArticleCard({item}:{item:Article}){return <Link className="vg-article-card" href={`/artikel/${item.slug}`}><span className="vg-eyebrow">PANDUAN GARUT</span><h3>{item.title}</h3><p>{item.excerpt}</p><small>{item.author} · {date(item.published_at||item.updated_at)}</small></Link>}
export function date(value:Date|string){return new Date(value).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'})}
export function TextContent({content}:{content:string}){return <div className="vg-prose">{content.split(/\n\s*\n/).filter(Boolean).map((block,i)=>block.startsWith('## ')?<h2 key={i}>{block.slice(3)}</h2>:<p key={i}>{block}</p>)}</div>}
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>}
export function Breadcrumbs({items}:{items:{name:string;path:string}[]}){return <><nav className="vg-breadcrumb" aria-label="Breadcrumb"><Link href="/">Beranda</Link>{items.map((item,i)=><span key={item.path}> / {i===items.length-1?item.name:<Link href={item.path}>{item.name}</Link>}</span>)}</nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Beranda',path:'/'},...items].map((it,i)=>({'@type':'ListItem',position:i+1,name:it.name,item:absoluteUrl(it.path)}))}}/></>}
