import Link from 'next/link'
import { Shell } from '@/components/mvp/Shell'
import { db } from '@/lib/mvp/db'
import { requireAdmin } from '@/lib/mvp/auth'
import { topics } from '@/lib/pulse/core'
import { sourceKinds } from '@/lib/pulse/research'
import { saveResearch } from './actions'
export const dynamic='force-dynamic'
export const metadata={title:'Riset tempat Community Pulse',robots:{index:false,follow:false}}
export default async function ResearchAdmin({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 await requireAdmin()
 const params=await searchParams,id=Number(params.edit)
 const [places,notes]=await Promise.all([db().query('SELECT id,name FROM vg_places ORDER BY name'),db().query('SELECT r.*,p.name AS place_name FROM vg_place_research r JOIN vg_places p ON p.id=r.place_id ORDER BY r.checked_at DESC,r.id LIMIT 300')])
 const item=id?(await db().query('SELECT * FROM vg_place_research WHERE id=$1',[id])).rows[0]:null
 function input(name:string,label:string,max:number,required=false){return <label>{label}<input name={name} maxLength={max} required={required} defaultValue={item?.[name]||''}/></label>}
 return <Shell><section className="vg-wrap vg-section"><div className="vg-section-heading"><div><span className="vg-eyebrow">ADMIN VISITGARUT</span><h1>Riset tempat & sumber</h1></div><Link href="/admin/pulse">Moderasi pengalaman pengunjung</Link></div><p>Tulis parafrasa editorial sendiri dari sumber yang diperiksa. Cantumkan tanggal sumber dan batasannya. Tandai saran sebagai saran VisitGarut. Catatan ini tidak memengaruhi sentimen, tren, atau jumlah pengalaman pengunjung.</p>{params.saved&&<p role="status" className="vg-alert success">Catatan riset tersimpan.</p>}{params.error&&<p role="alert" className="vg-alert">Belum tersimpan. Periksa sumber https, topik, judul, isi minimal 20 karakter, penerbit, tanggal, dan duplikasi sumber per topik.</p>}<div className="vg-admin-grid"><aside className="vg-admin-list"><Link className="vg-button" href="/admin/pulse/research">Tambah catatan riset</Link><small>Maksimal 300 catatan terakhir.</small>{notes.rows.map(r=><Link key={r.id} className={r.id===id?'active':''} href={`/admin/pulse/research?edit=${r.id}`}><strong>{r.title}</strong><small>{r.place_name} · {r.status}</small></Link>)}</aside><form className="vg-editor" action={saveResearch} key={id}><h2>{item?'Edit':'Tambah'} catatan</h2>{item&&<input type="hidden" name="id" value={item.id}/>}<label>Tempat<select name="place_id" defaultValue={item?.place_id} required>{places.rows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Topik<select name="topic" defaultValue={item?.topic||'aktivitas'}>{Object.entries(topics).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{input('title','Judul editorial',200,true)}<label>Catatan editorial<textarea name="summary" rows={6} minLength={20} maxLength={1200} required defaultValue={item?.summary||''}/></label>{input('source_url','URL sumber publik https',2000,true)}{input('publisher','Penerbit sumber',200,true)}<label>Jenis sumber<select name="source_kind" defaultValue={item?.source_kind||'authority'}>{Object.entries(sourceKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Tanggal publikasi (kosongkan bila tidak tercantum)<input type="date" name="source_published_at" defaultValue={item?.source_published_at?new Date(item.source_published_at).toISOString().slice(0,10):''}/></label><label>Batasan dan konteks<textarea name="limitations" maxLength={1200} rows={3} defaultValue={item?.limitations||''}/></label><label>Status<select name="status" defaultValue={item?.status||'pending'}><option value="pending">Antrean</option><option value="approved">Disetujui</option><option value="withdrawn">Ditarik</option></select></label><p>Menyimpan catatan memperbarui tanggal pemeriksaan sumber daring. Tarik catatan bila sumber berubah atau informasinya tidak lagi layak digunakan.</p><button className="vg-button">Simpan catatan riset</button></form></div></section></Shell>
}
