import Link from 'next/link'
import { Mountain,BedDouble,Utensils,Coffee,Car,Compass,MapPin } from 'lucide-react'
import { Shell,CategoryNav,SearchForm,PlaceGrid,ArticleCard,JsonLd } from '@/components/mvp/Shell'
import { places,articles,categories } from '@/lib/mvp/data'
import { siteUrl } from '@/lib/site'
export const dynamic='force-dynamic'
export const metadata={alternates:{canonical:'/'}}
const icons=[Mountain,BedDouble,Utensils,Coffee,Car,Compass]
export default async function Home(){const [items,guides]=await Promise.all([places(),articles()]);return <Shell><JsonLd data={{'@context':'https://schema.org','@type':'Organization',name:'VisitGarut',url:siteUrl}}/><JsonLd data={{'@context':'https://schema.org','@type':'WebSite',name:'VisitGarut',url:siteUrl}}/><section className="vg-hero"><div className="vg-wrap"><div className="vg-hero-label"><span/> JAWA BARAT, INDONESIA</div><h1>Ke Garut.<br/><em>Temukan cerita baru.</em></h1><p>Dari kawah pegunungan sampai tepi danau.<br/>Mulai perjalananmu dari tempat yang kamu suka.</p><SearchForm/><div className="vg-hero-links"><span>Mulai jelajahi:</span><Link href="/wisata">Wisata alam</Link><Link href="/artikel">Panduan perjalanan</Link><Link href="/map">Lihat peta</Link></div></div></section><section className="vg-wrap vg-section"><div className="vg-quick">{categories.map((c,i)=>{const Icon=icons[i];return <Link key={c.slug} href={`/${c.slug}`}><Icon size={25}/><span>{c.name}</span></Link>})}</div><div className="vg-section-heading"><div><span className="vg-eyebrow">KENALI GARUT LEBIH DEKAT</span><h2>Tempat untuk perjalananmu</h2></div><Link href="/search">Lihat semua tempat</Link></div><CategoryNav/><PlaceGrid items={items.slice(0,8)}/></section><section className="vg-map-banner vg-wrap"><div><MapPin size={28}/><h2>Satu peta. Banyak kemungkinan.</h2><p>Lihat lokasi tempat dan susun perjalanan berdasarkan wilayah.</p></div><Link className="vg-button" href="/map">Jelajahi peta</Link></section><section className="vg-wrap vg-section"><div className="vg-section-heading"><div><span className="vg-eyebrow">SEBELUM BERANGKAT</span><h2>Bekal perjalanan</h2></div><Link href="/artikel">Semua panduan</Link></div><div className="vg-article-grid">{guides.slice(0,3).map(a=><ArticleCard key={a.id} item={a}/>)}</div>{!guides.length&&<p>Panduan perjalanan akan segera ditambahkan.</p>}</section></Shell>}
