import Link from 'next/link'
import { Shell } from '@/components/mvp/Shell'
import { db } from '@/lib/mvp/db'
import { requireAdmin } from '@/lib/mvp/auth'
import { youtubeImportMessages,type YoutubeImportCode } from '@/lib/pulse/youtube-core'
import { collectionControl,reviewCollectedVideo,stageCollectedComment } from './actions'
export const dynamic='force-dynamic'
export const metadata={title:'YouTube lintas video — VisitGarut Admin',robots:{index:false,follow:false}}
const date=(d:Date|string)=>new Date(d).toLocaleString('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium'})
function apiError(code:string){return Object.hasOwn(youtubeImportMessages,code)?youtubeImportMessages[code as YoutubeImportCode]:'Pengumpulan belum selesai; antrean akan mencoba kembali.'}
export default async function YoutubeCollection({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 await requireAdmin();const params=await searchParams;const places=(await db().query("SELECT id,name FROM vg_places WHERE status='published' ORDER BY name")).rows
 const selected=places.find(p=>p.id===Number(params.place))||places.find(p=>p.name==='Gunung Papandayan')||places[0]
 if(!selected)return <Shell><p>Belum ada tempat yang diterbitkan.</p></Shell>
 const status=['pending','approved','rejected'].includes(params.status||'')?params.status!:'';const place=selected.id;const videoPage=Math.max(0,Math.min(10000,Math.trunc(Number(params.page)||0)));const [jobs,videoTotals,commentTotals,videoRows,sampleRows,usage,filteredTotals]=await Promise.all([
  db().query('SELECT * FROM vg_youtube_places WHERE place_id=$1',[place]),
  db().query("SELECT count(*)::int AS n,count(*) FILTER(WHERE review_status='approved')::int AS approved,count(*) FILTER(WHERE review_status='pending')::int AS pending,count(*) FILTER(WHERE NOT threads_done AND review_status<>'rejected')::int AS remaining FROM vg_youtube_videos WHERE place_id=$1 AND expires_at>now()",[place]),
  db().query('SELECT count(*)::int AS n,count(DISTINCT c.video_id)::int AS videos,count(*) FILTER(WHERE c.parent_key IS NOT NULL)::int AS replies FROM vg_youtube_comments c JOIN vg_youtube_videos v ON v.id=c.video_id WHERE v.place_id=$1 AND c.expires_at>now() AND v.expires_at>now()',[place]),
  db().query(`SELECT v.*,(SELECT count(*)::int FROM vg_youtube_comments c WHERE c.video_id=v.id AND c.expires_at>now()) AS comments FROM vg_youtube_videos v WHERE v.place_id=$1 AND v.expires_at>now() AND ($3='' OR v.review_status=$3) ORDER BY v.review_status='pending' DESC,v.id LIMIT 12 OFFSET $2`,[place,videoPage*12,status]),
  db().query(`WITH ranked AS (SELECT c.id,c.source_key,c.parent_key,c.author_name,c.original_text,c.published_at,c.video_id,v.video_id AS youtube_id,v.title,v.channel_title,v.review_status,parent.original_text AS parent_text,parent.author_name AS parent_author,row_number() OVER(PARTITION BY c.video_id ORDER BY md5(c.source_key),c.id) AS position FROM vg_youtube_comments c JOIN vg_youtube_videos v ON v.id=c.video_id LEFT JOIN vg_youtube_comments parent ON parent.video_id=c.video_id AND parent.source_key=c.parent_key AND parent.expires_at>now() WHERE v.place_id=$1 AND v.review_status<>'rejected' AND v.expires_at>now() AND c.expires_at>now() AND ($2::int IS NULL OR c.video_id=$2)) SELECT * FROM ranked ORDER BY position,video_id LIMIT 24`,[place,(Number.isSafeInteger(Number(params.video))&&Number(params.video)>0?Number(params.video):null)]),
  db().query("SELECT bucket,calls FROM vg_youtube_usage WHERE quota_day=(now() AT TIME ZONE 'America/Los_Angeles')::date"),
  db().query("SELECT count(*)::int AS n FROM vg_youtube_videos WHERE place_id=$1 AND expires_at>now() AND ($2='' OR review_status=$2)",[place,status])
 ])
 const job=jobs.rows[0],videos=videoTotals.rows[0],comments=commentTotals.rows[0],filtered=filteredTotals.rows[0].n;const pageUrl=(page:number)=>'/admin/pulse/youtube?place='+place+'&status='+status+'&page='+page+'#kandidat-video'
 return <Shell><section className="vg-wrap vg-section"><div className="vg-section-heading"><div><span className="vg-eyebrow">ADMIN COMMUNITY PULSE</span><h1>YouTube lintas video</h1></div><Link href="/admin/pulse">Moderasi bukti</Link></div>
 <p>Cari video berdasarkan nama dan alias lokasi, kumpulkan seluruh halaman komentar serta balasan yang tersedia lewat API, kemudian periksa sampel dari berbagai video. Hasil pencarian adalah kandidat; judul atau kata kunci belum membuktikan bahwa video membahas tempat yang benar.</p>
 <form method="get" className="vg-collection-toolbar"><label>Lokasi<select name="place" defaultValue={place}>{places.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="vg-button">Lihat lokasi</button></form>
 {params.saved&&<p className="vg-alert success" role="status">Perubahan tersimpan.</p>}{params.error&&<p className="vg-alert" role="alert">{params.error==='stage'?'Periksa relevansi video terlebih dahulu. Komentar tingkat atas sepanjang 20–4.000 karakter dapat disiapkan sebagai bukti; balasan diperiksa bersama konteks induknya.':'Perubahan belum tersimpan.'}</p>}
 <h2>{selected.name}</h2><div className="vg-admin-stats"><div><strong>{videos.n}</strong><small>Kandidat video</small></div><div><strong>{comments.n}</strong><small>Komentar & balasan tersimpan</small></div><div><strong>{comments.videos}</strong><small>Video dengan komentar</small></div><div><strong>{videos.pending}</strong><small>Video belum diperiksa</small></div></div><nav className="vg-collection-nav" aria-label="Bagian pengumpulan"><a href="#kandidat-video">Periksa relevansi video ↓</a><a href="#sampel-komentar">Baca sampel komentar ↓</a><Link href="/admin/pulse">Moderasi bukti ↗</Link></nav><p>Angka ini menunjukkan cakupan pengumpulan VisitGarut, bukan jumlah pengunjung atau penilaian lokasi.</p>
 <div className="vg-collection-status"><p>Antrean: {!job?'belum dimulai':!job.enabled?'dijeda':job.search_done?'pencarian selesai untuk kueri saat ini; komentar dan balasan dilanjutkan':'mencari video dan mengumpulkan komentar'}. {job?.last_run_at&&<>Diperiksa {date(job.last_run_at)}.</>}</p>{usage.rows.some(r=>r.bucket==='search'&&r.calls>=80)&&<p className="vg-alert">Batas pencarian hari ini tercapai. Pengambilan komentar dan balasan tetap berlanjut selama kuota data tersedia; pencarian dilanjutkan setelah pergantian hari Pacific.</p>}{job?.last_error&&job.last_error!=='youtube_daily_budget'&&<p className="vg-alert">{apiError(job.last_error)}</p>}
 <form action={collectionControl}><input type="hidden" name="place_id" value={place}/><div className="vg-actions"><button className="vg-button" name="mode" value="resume">Lanjutkan pengumpulan</button><button className="vg-button vg-secondary" name="mode" value="pause">Jeda</button><button className="vg-button vg-secondary" name="mode" value="restart">Cari ulang nama & alias</button></div></form></div>
 <details><summary>Cakupan pencarian dan kuota</summary><p>Pencarian memakai urutan relevansi dan terbaru serta pagination. YouTube tidak menjamin semua video tersedia di indeks pencarian. Video privat, dihapus, atau dengan komentar tertutup tidak dapat dikumpulkan. Komentar pendek tetap disimpan dalam kumpulan privat, tetapi tidak dipaksakan menjadi bukti ringkasan.</p><p>Pengumpulan berjalan bertahap setiap 7 menit, maksimal 8 langkah per proses. Batas internal harian: 80 pencarian dan 3.000 permintaan komentar/balasan. Hari kuota mengikuti waktu Pacific. Pemakaian worker hari ini: {usage.rows.find(r=>r.bucket==='search')?.calls||0} pencarian, {usage.rows.find(r=>r.bucket==='data')?.calls||0} permintaan data.</p><p>Metadata dan komentar API diperbarui atau dihapus sebelum 30 hari. Pencarian dijalankan ulang mingguan saat antrean mendapat giliran. Status relevansi yang sudah diperiksa dipertahankan.</p>{job&&<ul>{job.queries.map((q:{q:string;order:string},i:number)=><li key={i}>{q.q} · {q.order==='date'?'terbaru':'relevansi'}</li>)}</ul>}</details>
 <h2 id="kandidat-video">Kandidat video</h2><form method="get" className="vg-admin-filters"><input type="hidden" name="place" value={place}/><label>Status relevansi<select name="status" defaultValue={status}><option value="">Semua status</option><option value="pending">Belum diperiksa</option><option value="approved">Sesuai lokasi</option><option value="rejected">Tidak relevan</option></select></label><button className="vg-button">Tampilkan video</button></form><p>Menampilkan {videoRows.rows.length ? `${videoPage*12+1}–${Math.min((videoPage+1)*12,filtered)}` : '0'} dari {filtered} kandidat sesuai filter. Setujui hanya jika lokasi yang dibahas sesuai. Video yang ditolak dikeluarkan dari sampel dan pengumpulan berikutnya.</p><div className="pulse-research-grid">{videoRows.rows.map(v=><article className="pulse-evidence vg-review-card" key={v.id}><span className={`vg-status-tag ${v.review_status}`}>{v.review_status==='approved'?'Sesuai lokasi':v.review_status==='rejected'?'Tidak relevan':'Belum diperiksa'}</span><h3>{v.title}</h3><p>{v.channel_title} · Terbit {date(v.published_at)} · {v.comments} komentar tersimpan · {v.review_status==='approved'?'sesuai lokasi':v.review_status==='rejected'?'ditolak':'belum diperiksa'}</p><details><summary>Deskripsi video & pencarian</summary><p className="youtube-original">{v.description}</p><p>Kueri: {v.search_query}</p></details><p><a href={'https://www.youtube.com/watch?v='+v.video_id} target="_blank" rel="noopener noreferrer">Buka video asli</a> · <Link href={'/admin/pulse/youtube?place='+place+'&video='+v.id}>Komentar video ini</Link></p>{v.last_error&&<p>{apiError(v.last_error)}</p>}<form action={reviewCollectedVideo}><input type="hidden" name="video_id" value={v.id}/><div className="vg-actions"><button className="vg-button vg-secondary" name="status" value="approved">Sesuai lokasi</button><button className="vg-button vg-secondary" name="status" value="rejected">Tidak relevan</button><button className="vg-button vg-secondary" name="status" value="pending">Periksa lagi</button></div></form></article>)}</div>{!videoRows.rows.length&&<p className="vg-empty">Tidak ada kandidat dalam halaman atau filter ini. <Link href={pageUrl(0)}>Kembali ke halaman pertama</Link></p>}<nav className="vg-pager" aria-label="Halaman kandidat video">{videoPage>0&&<Link href={pageUrl(videoPage-1)}>← Sebelumnya</Link>}{filtered>(videoPage+1)*12&&<Link href={pageUrl(videoPage+1)}>Berikutnya →</Link>}</nav>
 <h2 id="sampel-komentar">Sampel komentar lintas video</h2><p>Menampilkan maksimal 24 komentar dengan giliran antarvideo, bukan hanya komentar populer dari satu video. Sampel ini untuk pemeriksaan, belum merupakan kesimpulan sentimen. Nama penulis komentar tidak membuktikan bahwa ia pernah berkunjung.</p><p>Analisis YouTube: {process.env.YOUTUBE_DERIVED_METRICS_APPROVAL_REFERENCE?'persyaratan metrik turunan tercatat; bukti tetap memerlukan moderasi':'belum aktif; persyaratan metrik turunan belum tercatat'}.</p>{params.video&&<p><Link href={'/admin/pulse/youtube?place='+place}>Kembali ke sampel lintas video</Link></p>}
 <div className="pulse-research-grid">{!sampleRows.rows.length&&<p>Belum ada komentar terkumpul. Antrean akan melanjutkan pencarian dan pengambilan komentar.</p>}{sampleRows.rows.map(c=><article className="pulse-evidence vg-review-card" key={c.id}><h3>{c.title}</h3><p>{c.channel_title} · {c.author_name} · {date(c.published_at)} · {c.parent_key?'balasan':'komentar tingkat atas'}</p>{c.parent_key&&<details><summary>Konteks komentar induk</summary><p>{c.parent_author}</p><blockquote>{c.parent_text||'Komentar induk belum tersedia dalam kumpulan ini. Buka percakapan asli untuk konteks lengkap.'}</blockquote></details>}<blockquote className="youtube-original">{c.original_text}</blockquote><p><a href={'https://www.youtube.com/watch?v='+c.youtube_id+'&lc='+encodeURIComponent(c.source_key)} target="_blank" rel="noopener noreferrer">Buka komentar asli di YouTube</a></p>{c.review_status!=='approved'?<p>Video perlu diperiksa kesesuaiannya dengan lokasi sebelum komentar disiapkan sebagai bukti.</p>:!c.parent_key&&Array.from(c.original_text).length>=20&&Array.from(c.original_text).length<=4000?<form action={stageCollectedComment}><input type="hidden" name="comment_id" value={c.id}/><button className="vg-button vg-secondary">Siapkan untuk pemeriksaan bukti</button></form>:<p>Gunakan konteks lengkap saat memeriksa balasan atau komentar pendek.</p>}</article>)}</div>
 </section></Shell>
}
