import Link from 'next/link'
import { notFound } from 'next/navigation'
import { MapPin,ExternalLink } from 'lucide-react'
import { Shell,Breadcrumbs,TextContent,JsonLd,PlaceGrid,ArticleCard,date } from '@/components/mvp/Shell'
import { place,places,relatedArticles,categories } from '@/lib/mvp/data'
import { absoluteUrl } from '@/lib/site'
export const dynamic='force-dynamic'
export async function generateMetadata({params}:{params:Promise<{category:string;slug:string}>}){const {category,slug}=await params;const p=await place(slug,category);return p?{title:`${p.name}, ${p.district} — Panduan Wisata`,description:p.excerpt,alternates:{canonical:`/${category}/${slug}`},openGraph:{title:p.name,description:p.excerpt,url:absoluteUrl(`/${category}/${slug}`),...(p.image_url?{images:[p.image_url]}:{})}}:{title:'Tempat tidak ditemukan',robots:{index:false}}}
export default async function Detail({params}:{params:Promise<{category:string;slug:string}>}){const {category,slug}=await params;if(!categories.some(c=>c.slug===category))notFound();const p=await place(slug,category);if(!p)notFound();const [other,guides]=await Promise.all([places({category}),relatedArticles(p.id)]);const c=categories.find(x=>x.slug===category)!;const schemaType=category==='wisata'?'TouristAttraction':category==='hotel'?'Hotel':category==='kuliner'?'Restaurant':category==='cafe'?'CafeOrCoffeeShop':'LocalBusiness';return <Shell><section className="vg-wrap vg-section"><Breadcrumbs items={[{name:c.name,path:`/${category}`},{name:p.name,path:`/${category}/${slug}`}]}/><JsonLd data={{'@context':'https://schema.org','@type':schemaType,'@id':absoluteUrl(`/${category}/${slug}#place`),name:p.name,description:p.excerpt,url:absoluteUrl(`/${category}/${slug}`),address:{'@type':'PostalAddress',streetAddress:p.address,addressLocality:p.district,addressRegion:'Jawa Barat',addressCountry:'ID'},...(p.latitude!==null&&p.longitude!==null?{geo:{'@type':'GeoCoordinates',latitude:p.latitude,longitude:p.longitude}}:{}),...(p.image_url?{image:p.image_url}:{}),...(p.website?{sameAs:[p.website]}:{})}}/><span className="vg-eyebrow">{c.name.toUpperCase()} · GARUT</span><h1>{p.name}</h1><p className="vg-location"><MapPin size={18}/>{p.district}, Garut</p>{p.image_url&&<figure className="vg-detail-image"><img src={p.image_url} alt={p.name}/>{p.image_credit&&<figcaption>{p.image_credit}</figcaption>}</figure>}<div className="vg-detail-grid"><article><p className="vg-intro">{p.excerpt}</p><TextContent content={p.content}/>{p.source_url&&<p className="vg-source"><a href={p.source_url} target="_blank" rel="noopener noreferrer">Baca sumber informasi <ExternalLink size={14}/></a></p>}<small>Diperbarui {date(p.updated_at)}</small></article><aside className="vg-info"><h2>Info kunjungan</h2><p><strong>Lokasi</strong><br/>{p.address||p.district+', Garut'}</p><p><strong>Tiket & jam buka</strong><br/>Konfirmasi informasi terbaru kepada pengelola.</p><a className="vg-button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name+' Garut')}`} target="_blank" rel="noopener noreferrer">Cari rute ke lokasi</a>{p.website&&<a href={p.website} target="_blank" rel="noopener noreferrer">Website pengelola</a>}{p.whatsapp&&<a href={`https://wa.me/${p.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noopener noreferrer">Hubungi via WhatsApp</a>}<Link href="/map">Lihat peta VisitGarut</Link></aside></div>{guides.length>0&&<section className="vg-section"><h2>Panduan terkait</h2><div className="vg-article-grid">{guides.map(a=><ArticleCard key={a.id} item={a}/>)}</div></section>}<section className="vg-section"><h2>Jelajahi tempat lain</h2><PlaceGrid items={other.filter(x=>x.id!==p.id).slice(0,3)}/></section></section></Shell>}
