const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const {PGlite}=require('@electric-sql/pglite')
const {buildPlacesQuery}=require('../.directory-test/search.js')
const {categoryHref}=require('../.directory-test/categories.js')
const {buildResearchSQL}=require('./seed-research.cjs')
;(async()=>{
 const pg=new PGlite()
 for(const name of ['001-mvp.sql','002-seed.sql','003-community-pulse.sql','004-place-research.sql'])await pg.exec(fs.readFileSync(path.join(__dirname,'../db',name),'utf8'))
 const rental=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/researched-rentals-2026-10-07.json'),'utf8'))
 const query=async options=>{const q=buildPlacesQuery(options);return (await pg.query(q.text,q.values)).rows}
 const before=(await query({})).length
 await pg.exec(buildResearchSQL(rental))
 assert.equal((await query({})).length,before+3)
 assert.equal((await query({category:'transportasi'})).length,3)
 assert.ok((await query({category:'transportasi'})).every(p=>p.latitude===null&&p.longitude===null))
 assert.equal((await pg.query('SELECT count(*)::int AS n FROM vg_social_mentions')).rows[0].n,0)
 console.log('PASS sourced rental import preserves original places and creates no visitor evidence or map pins')
 for(const q of ['rental','sewa kendaraan','transportasi garut'])assert.equal((await query({query:q})).length,3,q)
 assert.equal((await query({query:'rental motor'}))[0].slug,'ride-fun-rental-motor-garut')
 assert.equal((await query({query:'sewa mobil',category:'transportasi'})).length,2)
 assert.equal((await query({query:'rent car',category:'transportasi'})).length,2)
 assert.ok((await query({query:'penginapan'})).every(p=>p.category==='hotel'))
 console.log('PASS rental, vehicle searches, business aliases, and category vocabulary reach relevant results')
 const scoped=await query({query:'rental',category:'transportasi',district:'Cilawu',sort:'latest'})
 assert.equal(scoped.length,1);assert.equal(scoped[0].slug,'belian-group-rental-mobil-garut')
 assert.equal((await query({query:'rental',category:'hotel'})).length,0)
 assert.equal((await query({query:"' OR 1=1 --"})).length,0)
 await pg.query("UPDATE vg_places SET status='draft' WHERE slug='ride-fun-rental-motor-garut'")
 assert.equal((await query({query:'rental'})).length,2)
 console.log('PASS combined filters, query ordering, safe parameters, and unpublished listings remain protected')
 const changed=new URL(categoryHref('transportasi',{query:'mobil & motor',district:'Cilawu',sort:'latest'}),'https://visitgarut.com')
 assert.equal(changed.searchParams.get('q'),'mobil & motor');assert.equal(changed.searchParams.get('district'),'Cilawu');assert.equal(changed.searchParams.get('sort'),'latest');assert.equal(changed.searchParams.get('category'),'transportasi')
 assert.equal(categoryHref('transportasi'),'/transportasi')
 assert.equal(new URL(categoryHref('',{query:'mobil'}),'https://visitgarut.com').searchParams.has('category'),false)
 console.log('PASS switching categories keeps query, district, and sort with correct URL encoding')
 await pg.query("UPDATE vg_places SET excerpt='Owner edit' WHERE slug='belian-group-rental-mobil-garut'")
 await pg.exec(buildResearchSQL(rental))
 assert.equal((await query({})).length,before+2)
 assert.equal((await query({district:'Cilawu'}))[0].excerpt,'Owner edit')
 assert.equal((await pg.query('SELECT count(*)::int AS n FROM vg_place_research')).rows[0].n,6)
 console.log('PASS repeated rental import preserves owner edits, draft state, and research counts')
 await pg.close()
})().catch(e=>{console.error(e);process.exitCode=1})
