const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {calculatePulse,normalizeSocialUrl}=require(path.resolve(process.argv[2]));
const now=Date.parse('2026-10-07T12:00:00Z'),DAY=86400000;
const mention=(id,extra={})=>({id,platform:'visitgarut',original_text:`Pengalaman pengunjung uji ${id}: pemandangan indah dan jalan perlu diperhatikan.`,display_name:'Uji',source_url:`https://visitgarut.com/wisata/uji#pengalaman-${id}`,published_at:new Date(now-DAY).toISOString(),experience_date:null,sentiment:'mixed',status:'approved',rights_basis:'first_party',analysis_allowed:true,independence_key:'person-'+id,is_sensitive:false,verification_reference:'',engagement_count:0,expires_at:null,topics:[{topic:'pemandangan',sentiment:'positive'},{topic:'akses',sentiment:'negative'}],reviewed_at:new Date(now).toISOString(),...extra});
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name)}
test('Two mentions do not create a conclusion; three do',()=>{assert.equal(calculatePulse([mention(1),mention(2)],now).insights.length,0);assert.equal(calculatePulse([mention(1),mention(2),mention(3)],now).insights.length,2)});
test('Insight table remains available with honest empty and insufficient states',()=>{const empty=calculatePulse([],now);assert.equal(empty.topicStatuses.length,13);assert.ok(empty.topicStatuses.every(s=>s.count===0&&s.confidence==='belum cukup'&&s.evidenceIds.length===0));const small=calculatePulse([mention(1),mention(2)],now);const row=small.topicStatuses.find(s=>s.topic==='pemandangan');assert.equal(row.count,2);assert.equal(row.confidence,'belum cukup');assert.deepEqual(new Set(row.evidenceIds),new Set([1,2]));assert.equal(small.insights.length,0)});
test('Table counts reviewed independent people, never duplicate identities or unreviewed rows',()=>{const p=calculatePulse([mention(1),mention(2),mention(3,{independence_key:'person-1'}),mention(4,{reviewed_at:null}),mention(5,{analysis_allowed:false})],now);const row=p.topicStatuses.find(s=>s.topic==='pemandangan');assert.equal(row.count,2);assert.equal(p.classified,2);assert.ok(!row.evidenceIds.includes(4)&&!row.evidenceIds.includes(5))});
test('Ticket and traffic are distinct topics and premature sensitive reports stay private',()=>{const tickets=[mention(1,{topics:[{topic:'tiket',sentiment:'negative'}],original_text:'Penawaran tiket dibahas dalam pengalaman ini.',verification_reference:'checked'}),mention(2,{topics:[{topic:'tiket',sentiment:'negative'}]})];const p=calculatePulse(tickets,now);assert.equal(p.topicStatuses.find(s=>s.topic==='tiket').count,null);assert.deepEqual(p.topicStatuses.find(s=>s.topic==='tiket').evidenceIds,[]);assert.equal(p.evidence.length,0);const traffic=calculatePulse([1,2,3].map(i=>mention(i,{topics:[{topic:'lalu_lintas',sentiment:'negative'}]})),now);assert.equal(traffic.insights[0].topic,'lalu_lintas');assert.equal(traffic.insights[0].negative,3);assert.equal(traffic.topicStatuses.find(s=>s.topic==='tiket').count,0)});
test('Repeated author counts once and newest context wins',()=>{const p=calculatePulse([mention(1),mention(2),mention(3),mention(4,{independence_key:'person-1',published_at:new Date(now).toISOString()})],now);assert.equal(p.insights[0].count,3);assert.ok(p.insights[0].evidenceIds.includes(4));assert.ok(!p.insights[0].evidenceIds.includes(1))});
test('Mixed experience keeps separate positive and negative topics and full text',()=>{const p=calculatePulse([mention(1),mention(2),mention(3)],now);assert.equal(p.insights.find(i=>i.topic==='pemandangan').positive,3);assert.equal(p.insights.find(i=>i.topic==='akses').negative,3);assert.equal(p.evidence[0].original_text,mention(1).original_text);assert.equal(p.evidence[0].sentiment,'mixed')});
test('Percentage waits for ten and includes neutral and mixed denominator',()=>{assert.equal(calculatePulse(Array.from({length:9},(_,i)=>mention(i)),now).positivePercent,null);assert.equal(calculatePulse(Array.from({length:10},(_,i)=>mention(i,{sentiment:i<6?'positive':i<8?'neutral':'mixed'})),now).positivePercent,60)});
test('Pending, withdrawn, stale experience, and expired evidence cannot influence public output',()=>{const rows=[mention(1,{status:'pending'}),mention(2,{status:'withdrawn'}),mention(3,{expires_at:new Date(now-1).toISOString()}),mention(4,{experience_date:'2025-01-01'})];const p=calculatePulse(rows,now);assert.equal(p.evidence.length,0);assert.equal(p.classified,0)});
test('Approved yet unreviewed comments never enter public evidence',()=>{
 const rows=[mention(1),mention(2),mention(3),mention(4,{reviewed_at:null})]
 const p=calculatePulse(rows,now)
 assert.equal(p.insights.find(i=>i.topic==='pemandangan').count,3)
 assert.ok(!p.evidence.some(e=>e.id===4))
 assert.equal(p.evidence.length,3)
 const onlyUnreviewed=calculatePulse([mention(9,{reviewed_at:null})],now)
 assert.equal(onlyUnreviewed.evidence.length,0)
});
test('Permission and independent identity gate analysis',()=>{const p=calculatePulse([mention(1,{analysis_allowed:false}),mention(2,{independence_key:null}),mention(3,{platform:'google',analysis_allowed:false})],now);assert.equal(p.insights.length,0);assert.equal(p.classified,0)});
test('YouTube derived metrics stay blocked without explicit permission',()=>{const rows=[1,2,3].map(i=>mention(i,{platform:'youtube',rights_basis:'youtube_api',expires_at:new Date(now+DAY).toISOString()}));const blocked=calculatePulse(rows,now,false);assert.equal(blocked.insights.length,0);assert.equal(blocked.topicStatuses.find(s=>s.topic==='pemandangan').count,0);assert.equal(calculatePulse(rows,now,true).insights.length,2)});
test('Sensitive claims require six verified independent sources and two content sources',()=>{const rows=Array.from({length:6},(_,i)=>mention(i,{platform:'youtube',source_url:'https://www.youtube.com/watch?v='+ (i<3?'ABCDEFGHIJK':'LMNOPQRSTUV')+'&lc='+i,is_sensitive:true,verification_reference:'checked',topics:[{topic:'keamanan',sentiment:'negative'}]}));assert.equal(calculatePulse(rows.slice(0,5),now).evidence.length,0);assert.equal(calculatePulse(rows.map(m=>({...m,verification_reference:''})),now).evidence.length,0);assert.equal(calculatePulse(rows.map(m=>({...m,source_url:'https://www.youtube.com/watch?v=ABCDEFGHIJK&lc='+m.id})),now).insights.length,0);const p=calculatePulse(rows,now);assert.equal(p.insights[0].count,6);assert.equal(p.insights[0].sourceCount,2)});
test('Private identity and verification notes never enter public payload',()=>{const serialized=JSON.stringify(calculatePulse([mention(1),mention(2),mention(3)],now));for(const key of ['independence_key','verification_reference','rights_basis','permission_reference'])assert.ok(!serialized.includes(key))});
test('Trend needs both complete sample thresholds; high confidence needs cross-platform recent evidence',()=>{const rows=Array.from({length:15},(_,i)=>mention(i,{platform:i<8?'visitgarut':'instagram'}));assert.equal(calculatePulse(rows,now).insights[0].confidence,'tinggi');assert.equal(calculatePulse(rows,now).insights[0].trend,'belum cukup data');const periods=[...rows,...[20,21,22].map(i=>mention(i,{published_at:new Date(now-40*DAY).toISOString()}))];assert.equal(calculatePulse(periods,now).insights[0].trend,'naik')});
test('Source URL canonicalization rejects wrong hosts, credentials and arbitrary URLs',()=>{assert.equal(normalizeSocialUrl('https://youtu.be/ABCDEFGHIJK?si=tracking','youtube').url,'https://www.youtube.com/watch?v=ABCDEFGHIJK');for(const u of ['https://evil.example/watch?v=ABCDEFGHIJK','http://www.youtube.com/watch?v=ABCDEFGHIJK','https://username:password@youtube.com/watch?v=ABCDEFGHIJK','https://youtube.com:444/watch?v=ABCDEFGHIJK'])assert.throws(()=>normalizeSocialUrl(u,'youtube'));assert.throws(()=>normalizeSocialUrl('https://www.tiktok.com/@x','tiktok'))});
(async()=>{const {PGlite}=require('@electric-sql/pglite');const pg=new PGlite();for(const name of ['001-mvp.sql','002-seed.sql','003-community-pulse.sql','007-pulse-insight-topics.sql'])await pg.exec(fs.readFileSync(path.join(__dirname,'../db',name),'utf8'));const id=(await pg.query('SELECT id FROM vg_places LIMIT 1')).rows[0].id;const args=[id,'test','Pengalaman lengkap untuk pengujian basis data.','a'.repeat(64)];await pg.query("INSERT INTO vg_social_mentions(place_id,platform,source_key,original_text,fingerprint,published_at,rights_basis) VALUES($1,'visitgarut',$2,$3,$4,now(),'first_party')",args);assert.equal((await pg.query('SELECT status,analysis_allowed FROM vg_social_mentions')).rows[0].status,'pending');await assert.rejects(pg.query("INSERT INTO vg_social_mentions(place_id,platform,source_key,original_text,fingerprint,published_at,rights_basis) VALUES($1,'google','google','Ulasan yang tidak boleh disalin ke direktori ini.','b',now(),'licensed')",[id]));await pg.query("INSERT INTO vg_mention_topics(mention_id,topic,sentiment) SELECT id,'lalu_lintas','negative' FROM vg_social_mentions");await pg.query("INSERT INTO vg_mention_topics(mention_id,topic,sentiment) SELECT id,'tiket','negative' FROM vg_social_mentions");await assert.rejects(pg.query("INSERT INTO vg_mention_topics(mention_id,topic,sentiment) SELECT id,'unrecognized_topic','neutral' FROM vg_social_mentions"));console.log('PASS PostgreSQL migrations and evidence constraints');await pg.close();console.log(`${checks+1} Community Pulse checks passed`)})().catch(e=>{console.error(e);process.exitCode=1});
